# Default values for efk.
# .../ helm-charts/kibana/values.yaml
kibana:
  image:
    repository: "docker.elastic.co/kibana/kibana-oss"
    tag: "6.1.3"
  env:
    # All Kibana configuration options are adjustable via env vars.
    # To adjust a config option to an env var uppercase + replace `.` with `_`
    # Ref: https://www.elastic.co/guide/en/kibana/current/settings.html

    ELASTICSEARCH_URL: http://efk-cloud-stack:9200
    SERVER_PORT: 5601
    LOGGING_VERBOSE: "true"
    SERVER_DEFAULTROUTE: "/app/kibana"
# .../helm-charts/elasticsearch/values.yaml
elasticsearch:
  image:
    repository: upmcenterprises/docker-elasticsearch-kubernetes
    tag: "6.1.3_0"
  name: efk-cluster
  clientReplicas: 1
  masterReplicas: 1
  dataReplicas: 1
  dataVolumeSize: 1Gi
  javaOpts: "-Xms1024m -Xmx1024m"
  resources:
    requests:
      memory: 1024Mi
      cpu: 200m
    limits:
      memory: 2048Mi
      cpu: '1'

# .../charts/fluent-bit/values.yaml
fluent-bit:
  image:
    fluent_bit:
      repository: custom/fluent-bit
      tag: 0.13.0
  backend:
    type: es
    es:
      host: efk-cloud-stack
      port: 9200
  rbac:
    create: true