#Assumed helm is already installed.
#serviceAccount creaed in the kube-system namespace can restrict to cloud_log namespace for finite control 

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tools-repo-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: tools-repo
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""