
apiVersion: ceph.rook.io/v1beta1
kind: Cluster
metadata:
  name: cloud_log
  namespace: cloud_log
spec:
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: false
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"